# Generated by Django 4.2.4 on 2023-08-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_nnenu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NNenu',
        ),
    ]
